<a href="https://colab.research.google.com/github/Zebo616/Attack-Lab/blob/master/Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets
from sklearn import metrics
from sklearn import preprocessing
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, cross_val_predict
from sklearn.metrics import accuracy_score, roc_auc_score, roc_curve, classification_report, confusion_matrix
from sklearn.naive_bayes import GaussianNB

Here we read in the data.

We will use three different data sets: the data set with only the original features, the data set with only the feature engineered "team sum/average" values previously computed, and a third dataset with both of these.

In [6]:
# the entire dataset
data = pd.read_csv("3000_engineered_data.csv", header=0)
data.head()

b1_champ_id  b2_champ_id  ...  r_champ_player_win_diff  winner
0           34          203  ...                 0.270394       r
1           23           67  ...                 0.440548       b
2           99          222  ...                -0.064419       r
3          122          119  ...                 0.613805       r
4           75           25  ...                -1.453228       b

[5 rows x 85 columns]

In [7]:
# only feature engineered items
data_teams = data.iloc[:,-15:]
data_teams.head()

b_win_sum  r_win_sum  ...  r_champ_player_win_diff  winner
0   2.914206   2.931831  ...                 0.270394       r
1   2.759413   2.974894  ...                 0.440548       b
2   2.705163   2.491890  ...                -0.064419       r
3   2.983542   3.236344  ...                 0.613805       r
4   2.407700   1.195451  ...                -1.453228       b

[5 rows x 15 columns]

In [8]:
# the original features data set
data_original = data.iloc[:,:-15]
data_original['winner'] = data.iloc[:,-1]
data_original.head()

b1_champ_id  b2_champ_id  ...  r10_champ_win_rate  winner
0           34          203  ...            0.518675       r
1           23           67  ...            0.554777       b
2           99          222  ...            0.420000       r
3          122          119  ...            0.534542       r
4           75           25  ...            0.545546       b

[5 rows x 71 columns]

First, we'll split the datasets into features and class labels.

data[name]_X will contain the features, and data[name]_Y will contain the class labels.

We will have to convert the class labels to binary for scikit-learn to be able to work with them. We will arbitrarily say 0 means the blue team wins, and 1 means the red team wins.

In [9]:
# data prep for data
data_Y = data['winner']
data_Y = data_Y.values.ravel()
data_X = data.drop(['winner'],axis=1)
print(data_X.head)
print()
print("data_Y pre-binarization: ", data_Y)

# binarize data_Y
binarizer = preprocessing.LabelBinarizer()
data_Y = binarizer.fit_transform(data_Y)
data_Y = np.rot90(data_Y)
data_Y = data_Y[0]
print("data_Y post-binarization: ", data_Y)

<bound method NDFrame.head of       b1_champ_id  ...  r_champ_player_win_diff
0              34  ...                 0.270394
1              23  ...                 0.440548
2              99  ...                -0.064419
3             122  ...                 0.613805
4              75  ...                -1.453228
...           ...  ...                      ...
2925          887  ...                 0.037825
2926          222  ...                 0.004268
2927          122  ...                 0.706182
2928           12  ...                 0.127274
2929           27  ...                 0.540623

[2930 rows x 84 columns]>

data_Y pre-binarization:  ['r' 'b' 'r' ... 'r' 'r' 'b']
data_Y post-binarization:  [1 0 1 ... 1 1 0]


In [13]:
# data prep for data_teams
data_teams_Y = data_teams['winner']
data_teams_Y = data_teams_Y.values.ravel()
data_teams_X = data_teams.drop(['winner'],axis=1)
print(data_teams_X.head)
print()
print("data_teams_Y pre-binarization: ", data_teams_Y)

# binarize data_teams_Y
binarizer = preprocessing.LabelBinarizer()
data_teams_Y = binarizer.fit_transform(data_teams_Y)
data_teams_Y = np.rot90(data_teams_Y)
data_teams_Y = data_teams_Y[0]
print("data_teams_Y post-binarization: ", data_teams_Y)

<bound method NDFrame.head of       b_win_sum  r_win_sum  ...  b_champ_player_win_diff  r_champ_player_win_diff
0      2.914206   2.931831  ...                 0.389538                 0.270394
1      2.759413   2.974894  ...                 0.138329                 0.440548
2      2.705163   2.491890  ...                 0.064698                -0.064419
3      2.983542   3.236344  ...                 0.368309                 0.613805
4      2.407700   1.195451  ...                -0.180283                -1.453228
...         ...        ...  ...                      ...                      ...
2925   2.509286   2.684566  ...                -0.038688                 0.037825
2926   2.792108   2.498352  ...                 0.222891                 0.004268
2927   2.557505   3.361648  ...                -0.087729                 0.706182
2928   1.594672   2.754835  ...                -0.920140                 0.127274
2929   2.993461   3.086309  ...                 0.434805            

In [12]:
# data prep for data_original
data_original_Y = data_original['winner']
data_original_Y = data_original_Y.values.ravel()
data_original_X = data_original.drop(['winner'],axis=1)
print(data_original_X.head)
print()
print("data_original_Y pre-binarization: ", data_original_Y)

# binarize data_original_Y
binarizer = preprocessing.LabelBinarizer()
data_original_Y = binarizer.fit_transform(data_original_Y)
data_original_Y = np.rot90(data_original_Y)
data_original_Y = data_original_Y[0]
print("data_original_Y post-binarization: ", data_original_Y)

<bound method NDFrame.head of       b1_champ_id  b2_champ_id  ...  r9_champ_win_rate  r10_champ_win_rate
0              34          203  ...           0.557449            0.518675
1              23           67  ...           0.434316            0.554777
2              99          222  ...           0.514967            0.420000
3             122          119  ...           0.422799            0.534542
4              75           25  ...           0.519789            0.545546
...           ...          ...  ...                ...                 ...
2925          887           63  ...           0.513538            0.547719
2926          222          875  ...           0.514967            0.420000
2927          122          105  ...           0.533896            0.554777
2928           12           39  ...           0.506626            0.529065
2929           27          234  ...           0.457430            0.496690

[2930 rows x 70 columns]>

data_original_Y pre-binarization:  ['r' 'b

Finally, we'll look at how a naive bayes classifier handles each dataset and compare results. We'll use 10-fold cross validation.

In [24]:
# combined dataset
clf = GaussianNB()
nested_score = cross_val_score(clf, data_X, data_Y, cv=10)
print("Accuracy:", nested_score.mean()*100)
print()

pred = cross_val_predict(clf, data_X, data_Y, cv=10)
cm = confusion_matrix(data_Y, pred)
print(cm)
print(classification_report(data_Y, pred))

Accuracy: 55.52901023890785

[[631 838]
 [465 996]]
              precision    recall  f1-score   support

           0       0.58      0.43      0.49      1469
           1       0.54      0.68      0.60      1461

    accuracy                           0.56      2930
   macro avg       0.56      0.56      0.55      2930
weighted avg       0.56      0.56      0.55      2930



In [25]:
# feature engineered dataset
clf = GaussianNB()
nested_score = cross_val_score(clf, data_teams_X, data_teams_Y, cv=10)
print("Accuracy:", nested_score.mean()*100)
print()

pred = cross_val_predict(clf, data_teams_X, data_teams_Y, cv=10)
cm = confusion_matrix(data_teams_Y, pred)
print(cm)
print(classification_report(data_teams_Y, pred))

Accuracy: 58.97610921501707

[[751 718]
 [484 977]]
              precision    recall  f1-score   support

           0       0.61      0.51      0.56      1469
           1       0.58      0.67      0.62      1461

    accuracy                           0.59      2930
   macro avg       0.59      0.59      0.59      2930
weighted avg       0.59      0.59      0.59      2930



In [26]:
# original features dataset
clf = GaussianNB()
nested_score = cross_val_score(clf, data_original_X, data_original_Y, cv=10)
print("Accuracy:", nested_score.mean()*100)
print()

pred = cross_val_predict(clf, data_original_X, data_original_Y, cv=10)
cm = confusion_matrix(data_original_Y, pred)
print(cm)
print(classification_report(data_original_Y, pred))

Accuracy: 53.78839590443685

[[593 876]
 [478 983]]
              precision    recall  f1-score   support

           0       0.55      0.40      0.47      1469
           1       0.53      0.67      0.59      1461

    accuracy                           0.54      2930
   macro avg       0.54      0.54      0.53      2930
weighted avg       0.54      0.54      0.53      2930



Based on these results, we see that the original features dataset ranks lowest in accuracy, and that the dataset with only the engineered features ranked highest in accuracy. This was expected because, as previously discussed, each team member listed is in an arbitrary position in the dataset (i.e. there is no meaningful systematic difference between player r4 and player r5; they could be switched without a problem). Therefore, combining these arbitrary features into either an average or sum for each team improved accuracy for the classifier.